@host = http://localhost:5044

### Get all users
GET {{host}}/users
Accept: application/json

### Get a single user
GET {{host}}/users/1
Accept: application/json

### Get a user that does not exist (404)
GET {{host}}/users/999
Accept: application/json

### Create a user (201 Created)
POST {{host}}/users
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "username": "ada",
  "email": "ada@calc.io",
  "phone": "555-0001",
  "website": "ada.dev"
}

### Create a user with missing/invalid fields (400 Bad Request)
POST {{host}}/users
Content-Type: application/json

{
  "username": "nobody"
}

### Update a user (200 OK)
PUT {{host}}/users/1
Content-Type: application/json

{
  "name": "Leanne Graham",
  "username": "Bret",
  "email": "leanne@updated.io",
  "phone": "1-770-736-8031 x56442",
  "website": "hildegard.org"
}

### Update a user that does not exist (404)
PUT {{host}}/users/999
Content-Type: application/json

{
  "name": "Nobody",
  "username": "nobody",
  "email": "nobody@nowhere.io"
}

### Delete a user (204 No Content)
DELETE {{host}}/users/1

### Delete a user that does not exist (404)
DELETE {{host}}/users/999

###
